### ISSUE TITLE
syntax error in format string

### ISSUE THREAD

**Issue by donovan-jasper** [exploide/bloodhound-cli#1]
line 20 in cypher.py 

' -> "

**Comment by donovan-jasper** [comment]
fix is very simple:

`return f"[{', '.join(escaped_list)}]"
`instead of
`return f'[{', '.join(escaped_list)}]'
`

thanks for making this great tool!

**Comment by exploide** [comment]
My first thought was "how can this happen, I tested it".

Turns out, while you can reuse quotation marks inside format string placeholders with Python 3.12, you cannot on older versions. Pushed a fix. Thank you for reporting it!

> thanks for making this great tool!

Cool :) I was a bit surprised that someone is already using it :grin:
